[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/lucky"
  to = "/lucky.html"
  status = 200

[dev]
  command = "python app.py"
  port = 5000
  publish = "." 